run: complile
	./exercice11
	./exercice12
	./exercice13
	./exercice14
	
compile: exercice11.c	exercice12.c	exercice13.c	exercice14.c

	gcc -o exercice11 -Wall exercice11.c
	gcc -o exercice12 -Wall exercice12.c
	gcc -o exercice13 -Wall exercice13.c	
	gcc -o exercice14 -Wall exercice14.c
