run: compile
	./exercice17 
	./exercice18 
	
compile: exercice17.c	exercice18.c

	gcc -o exercice17 -Wall exercice17.c
	gcc -o exercice18 -Wall exercice18.c

test:
	./exercice17 6.2 -8 2.0
	./exercice18 Theophile Thomas
