run: compile
	./exercice23
	./exercice24
	./exercice25
	./exercice27
	
compile: exercice23.c	exercice24.c	exercice25.c	exercice27.c

	gcc -o exercice23 -Wall exercice23.c
	gcc -o exercice24 -Wall exercice24.c
	gcc -o exercice25 -Wall exercice25.c		
	gcc -o exercice27 -Wall exercice27.c	
		
clean:
	rm -f exercice23
	rm -f exercice24
	rm -f exercice25
	rm -f exercice27
