run: compile
	./exercice19
	./exercice20
	./exercice21

compile: exercice19.c	exercice20.c	exercice21.c

	gcc -o exercice19 -Wall exercice19.c
	gcc -o exercice20 -Wall exercice20.c
	gcc -o exercice21 -Wall exercice21.c
	
clean:
	rm -f exercice19
	rm -f exercice20
	rm -f exercice21
